version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: my_container_db
    environment:
      POSTGRES_DB: my_store
      POSTGRES_USER: mauro
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
    volumes:
      - /postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: maxdn@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80


